import{createContext,useContext,useEffect,useState,type FormEvent,type ReactNode}from"react";
import{Link,Navigate,NavLink,Route,Routes,useNavigate,useParams,useSearchParams}from"react-router-dom";
import{api,ApiClientError,type Appointment,type Patient,type User}from"./api";
type AuthValue={user:User|null;loading:boolean;login:(e:string,p:string)=>Promise<void>;logout:()=>Promise<void>};
const AuthContext=createContext<AuthValue|null>(null);const useAuth=()=>useContext(AuthContext)!;
function AuthProvider({children}:{children:ReactNode}){const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{api<{user:User}>("/auth/me").then(x=>setUser(x.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]);async function login(email:string,password:string){const x=await api<{user:User}>("/auth/login",{method:"POST",body:JSON.stringify({email,password})});setUser(x.user)}async function logout(){await api("/auth/logout",{method:"POST"});setUser(null)}return <AuthContext.Provider value={{user,loading,login,logout}}>{children}</AuthContext.Provider>}
function Protected({children}:{children:ReactNode}){const{user,loading}=useAuth();if(loading)return <div className="center">Chargement…</div>;return user?children:<Navigate to="/login" replace/>}
function Layout({children}:{children:ReactNode}){const{user,logout}=useAuth();return <div className="app-shell"><aside><Link className="brand" to="/"><i>+</i> ClinicFlow</Link><nav><NavLink to="/">Vue du jour</NavLink><NavLink to="/patients">Patients</NavLink><NavLink to="/appointments">Rendez-vous</NavLink></nav><div className="profile"><span>{user?.email}</span><small>{user?.role==="admin"?"Administrateur":"Équipe"}</small><button className="link-button" onClick={()=>void logout()}>Se déconnecter</button></div></aside><main className="content">{children}</main></div>}
function Login(){const{user,login}=useAuth();const navigate=useNavigate();const[error,setError]=useState("");const[busy,setBusy]=useState(false);if(user)return <Navigate to="/" replace/>;async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await login(String(f.get("email")),String(f.get("password")));navigate("/")}catch(x){setError(x instanceof Error?x.message:"Connexion impossible.")}finally{setBusy(false)}}return <main className="login-page"><section className="login-copy"><span className="eyebrow">CLINICFLOW</span><h1>Chaque patient.<br/>Au bon moment.</h1><p>Un espace calme pour organiser une journée de clinique bien remplie.</p></section><form className="card login-card" onSubmit={submit}><h2>Bienvenue</h2><p>Connectez-vous à votre espace.</p><label>Email<input name="email" type="email" defaultValue="admin@clinicflow.local" required/></label><label>Mot de passe<input name="password" type="password" defaultValue="ClinicFlow2026!" required minLength={8}/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Connexion…":"Se connecter"}</button></form></main>}
function Dashboard(){const[stats,setStats]=useState<Record<string,number>|null>(null);const[items,setItems]=useState<Appointment[]>([]);useEffect(()=>{const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Casablanca",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());Promise.all([api<{data:Record<string,number>}>("/dashboard"),api<{data:Appointment[]}>(`/appointments?date=${today}&limit=100`)]).then(([a,b])=>{setStats(a.data);setItems(b.data)})},[]);return <Layout><PageTitle eyebrow="AUJOURD’HUI · CASABLANCA" title="Bonjour, voici votre journée." action={<Link className="button" to="/appointments">+ Nouveau rendez-vous</Link>}/><div className="stats">{[["Patients",stats?.totalPatients],["Aujourd’hui",stats?.appointmentsToday],["En attente",stats?.pending],["Confirmés",stats?.confirmed]].map(([l,v])=><article className="card stat" key={String(l)}><strong>{v??"—"}</strong><span>{l}</span></article>)}</div><section className="card section"><div className="section-head"><h2>Agenda du jour</h2><Link to="/appointments">Voir tout</Link></div><AppointmentTable appointments={items}/></section></Layout>}
function Patients(){const[search,setSearch]=useState("");const[page,setPage]=useState(1);const[result,setResult]=useState<{data:Patient[];pagination:{total:number;totalPages:number}}|null>(null);const[show,setShow]=useState(false);const[error,setError]=useState("");const load=()=>api<NonNullable<typeof result>>(`/patients?search=${encodeURIComponent(search)}&page=${page}&limit=10`).then(setResult);useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[search,page]);async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/patients",{method:"POST",body:JSON.stringify({fullName:f.get("fullName"),cin:f.get("cin"),phone:f.get("phone"),birthDate:f.get("birthDate"),address:f.get("address")||null})});setShow(false);await load()}catch(x){setError(x instanceof Error?x.message:"Création impossible.")}}return <Layout><PageTitle eyebrow="RÉPERTOIRE" title="Patients" action={<button onClick={()=>setShow(!show)}>+ Ajouter un patient</button>}/>{show&&<form className="card form-grid" onSubmit={create}><h2>Nouveau patient</h2><label>Nom complet<input name="fullName" required/></label><label>CIN<input name="cin" required/></label><label>Téléphone<input name="phone" required/></label><label>Date de naissance<input name="birthDate" type="date" required/></label><label className="wide">Adresse<input name="address"/></label>{error&&<div className="error wide">{error}</div>}<div className="actions wide"><button type="button" className="secondary" onClick={()=>setShow(false)}>Annuler</button><button>Enregistrer</button></div></form>}<section className="card section"><div className="toolbar"><input placeholder="Rechercher par nom ou CIN…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><span>{result?.pagination.total??0} patients</span></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>CIN</th><th>Téléphone</th><th/></tr></thead><tbody>{result?.data.map(p=><tr key={p.id}><td><b>{p.fullName}</b></td><td>{p.cin}</td><td>{p.phone}</td><td><Link to={`/patients/${p.id}`}>Consulter →</Link></td></tr>)}</tbody></table></div>{result?.data.length===0&&<Empty text="Aucun patient trouvé."/>}<div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(x=>x-1)}>Précédent</button><span>Page {page} / {Math.max(1,result?.pagination.totalPages??1)}</span><button className="secondary" disabled={page>=(result?.pagination.totalPages??1)} onClick={()=>setPage(x=>x+1)}>Suivant</button></div></section></Layout>}
function PatientDetails(){
  const{id}=useParams();
  const{user}=useAuth();
  const navigate=useNavigate();
  const[p,setP]=useState<Patient|null>(null);
  const[items,setItems]=useState<Appointment[]>([]);
  const[editing,setEditing]=useState(false);
  const[confirmArchive,setConfirmArchive]=useState(false);
  const[archiving,setArchiving]=useState(false);
  const[cancelling,setCancelling]=useState<string|null>(null);
  const[actionError,setActionError]=useState("");
  const blockingAppointments=items.filter(item=>item.status!=="cancelled"&&new Date(item.appointmentDate)>=new Date());
  const load=()=>Promise.all([api<{data:Patient}>(`/patients/${id}`),api<{data:Appointment[]}>(`/appointments?patientId=${id}&limit=100`)]).then(([a,b])=>{setP(a.data);setItems(b.data)});
  useEffect(()=>{void load()},[id]);
  useEffect(()=>{if(!confirmArchive)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setConfirmArchive(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[confirmArchive]);
  async function save(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setActionError("");const f=new FormData(e.currentTarget);
    try{await api(`/patients/${id}`,{method:"PUT",body:JSON.stringify({fullName:f.get("fullName"),cin:f.get("cin"),phone:f.get("phone"),birthDate:f.get("birthDate"),address:f.get("address")||null})});setEditing(false);await load()}
    catch(error){setActionError(error instanceof Error?error.message:"Modification impossible.")}
  }
  async function archive(){
    setArchiving(true);setActionError("");
    try{await api(`/patients/${id}`,{method:"DELETE"});navigate("/patients",{replace:true})}
    catch(error){setActionError(error instanceof Error?error.message:"Archivage impossible.")}
    finally{setArchiving(false)}
  }
  async function cancelBlockingAppointment(appointmentId:string){
    setCancelling(appointmentId);setActionError("");
    try{await api(`/appointments/${appointmentId}/status`,{method:"PATCH",body:JSON.stringify({status:"cancelled"})});await load()}
    catch(error){setActionError(error instanceof Error?error.message:"Annulation impossible.")}
    finally{setCancelling(null)}
  }
  async function cancelAllBlockingAppointments(){
    setCancelling("all");setActionError("");
    try{await Promise.all(blockingAppointments.map(appointment=>api(`/appointments/${appointment.id}/status`,{method:"PATCH",body:JSON.stringify({status:"cancelled"})})));await load()}
    catch(error){setActionError(error instanceof Error?error.message:"Certains rendez-vous n’ont pas pu être annulés.");await load()}
    finally{setCancelling(null)}
  }
  return <Layout>
    <PageTitle eyebrow="DOSSIER PATIENT" title={p?.fullName??"Chargement…"} action={<Link className="button" to={`/appointments?patientId=${id}`}>+ Prendre rendez-vous</Link>}/>
    <div className="details-grid">
      <section className="card section">
        <div className="section-head"><h2>Informations</h2><button className="secondary" onClick={()=>{setEditing(!editing);setActionError("")}}>{editing?"Annuler":"Modifier"}</button></div>
        {editing&&p?<form className="detail-form" onSubmit={save}><label>Nom<input name="fullName" defaultValue={p.fullName}/></label><label>CIN<input name="cin" defaultValue={p.cin}/></label><label>Téléphone<input name="phone" defaultValue={p.phone}/></label><label>Naissance<input name="birthDate" type="date" defaultValue={p.birthDate.slice(0,10)}/></label><label>Adresse<input name="address" defaultValue={p.address??""}/></label><div className="detail-form-actions"><button>Enregistrer</button></div></form>:<dl><dt>CIN</dt><dd>{p?.cin}</dd><dt>Téléphone</dt><dd>{p?.phone}</dd><dt>Naissance</dt><dd>{p?.birthDate.slice(0,10)}</dd><dt>Adresse</dt><dd>{p?.address||"Non renseignée"}</dd></dl>}
        {actionError&&<div className="error patient-action-error" role="alert">{actionError}</div>}
        {user?.role==="admin"&&<div className="archive-zone"><div><strong>Archiver ce patient</strong><p>Le patient disparaîtra des listes actives. Son historique sera conservé.</p></div><button className="danger-outline" onClick={()=>{setConfirmArchive(true);setActionError("")}}>{blockingAppointments.length?`Gérer ${blockingAppointments.length} rendez-vous et archiver`:"Archiver"}</button></div>}
      </section>
      <section className="card section"><h2>Historique</h2><AppointmentTable appointments={items}/></section>
    </div>
    {confirmArchive&&<div className="modal-backdrop" onMouseDown={()=>setConfirmArchive(false)}><section className="archive-modal" role="dialog" aria-modal="true" aria-labelledby="archive-modal-title" onMouseDown={event=>event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">ACTION ADMINISTRATEUR</span><h2 id="archive-modal-title">Archiver {p?.fullName}</h2></div><button className="modal-close" aria-label="Fermer" onClick={()=>setConfirmArchive(false)}>×</button></div>{blockingAppointments.length>0?<div className="archive-blockers"><div className="archive-blockers-heading"><div><strong>{blockingAppointments.length} rendez-vous futur{blockingAppointments.length>1?"s":""} à annuler</strong><p>Annulez-les sans quitter cette fenêtre pour poursuivre l’archivage.</p></div>{blockingAppointments.length>1&&<button className="secondary" disabled={cancelling!==null} onClick={()=>void cancelAllBlockingAppointments()}>{cancelling==="all"?"Annulation…":"Tout annuler"}</button>}</div><ul>{blockingAppointments.map(appointment=><li key={appointment.id}><div><strong>{new Intl.DateTimeFormat("fr-MA",{timeZone:"Africa/Casablanca",dateStyle:"medium",timeStyle:"short"}).format(new Date(appointment.appointmentDate))}</strong><span>{appointment.reason} · {appointment.status==="confirmed"?"Confirmé":"En attente"}</span></div><button className="secondary" disabled={cancelling!==null} onClick={()=>void cancelBlockingAppointment(appointment.id)}>{cancelling===appointment.id?"Annulation…":"Annuler"}</button></li>)}</ul></div>:<div className="archive-ready"><p>Aucun rendez-vous futur actif ne bloque l’archivage. L’historique sera conservé.</p><div><button className="secondary" disabled={archiving} onClick={()=>setConfirmArchive(false)}>Retour</button><button className="danger" disabled={archiving} onClick={()=>void archive()}>{archiving?"Archivage…":"Confirmer l’archivage"}</button></div></div>}{actionError&&<div className="error" role="alert">{actionError}</div>}</section></div>}
  </Layout>
}
function Appointments(){
  const[params]=useSearchParams();
  const[items,setItems]=useState<Appointment[]>([]);
  const[patients,setPatients]=useState<Patient[]>([]);
  const[selectedPatientId,setSelectedPatientId]=useState(params.get("patientId")??"");
  const[date,setDate]=useState("");
  const[status,setStatus]=useState("");
  const[page,setPage]=useState(1);
  const[pagination,setPagination]=useState({total:0,totalPages:1});
  const[error,setError]=useState("");
  const[success,setSuccess]=useState("");
  const selectedPatient=patients.find(patient=>patient.id===selectedPatientId);
  const load=(nextDate=date,nextStatus=status,nextPage=page)=>api<{data:Appointment[];pagination:{total:number;totalPages:number}}>(`/appointments?date=${nextDate}&status=${nextStatus}&page=${nextPage}&limit=10`).then(x=>{setItems(x.data);setPagination({total:x.pagination.total,totalPages:Math.max(1,x.pagination.totalPages)})});
  useEffect(()=>{void load();api<{data:Patient[]}>("/patients?limit=100").then(x=>setPatients(x.data))},[date,status,page]);
  async function create(e:FormEvent<HTMLFormElement>){
    e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const localDateTime=String(f.get("appointmentDate"));setError("");setSuccess("");
    try{const created=await api<{data:Appointment}>("/appointments",{method:"POST",body:JSON.stringify({patientId:selectedPatientId,appointmentDate:new Date(localDateTime).toISOString(),status:f.get("status"),reason:f.get("reason"),notes:f.get("notes")||null})});const createdDate=localDateTime.slice(0,10);form.reset();setSelectedPatientId("");setDate(createdDate);setStatus("");setPage(1);await load(createdDate,"",1);setSuccess(`Rendez-vous de ${created.data.patientName} enregistré et affiché ci-dessous.`)}
    catch(x){setError(x instanceof ApiClientError?x.message:"Création impossible.")}
  }
  async function change(id:string,next:string){setError("");setSuccess("");try{await api(`/appointments/${id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});await load()}catch(x){setError(x instanceof Error?x.message:"Modification impossible.")}}
  return <Layout><PageTitle eyebrow="PLANIFICATION" title="Rendez-vous"/><form className="card appointment-form" onSubmit={create}><h2>Nouveau rendez-vous</h2><label>Patient<select name="patientId" value={selectedPatientId} onChange={e=>setSelectedPatientId(e.target.value)} required><option value="" disabled>Sélectionner…</option>{patients.map(p=><option key={p.id} value={p.id}>{p.fullName} · {p.cin}</option>)}</select></label><label>Date et heure<input name="appointmentDate" type="datetime-local" required/></label>{selectedPatient&&<div className="patient-preview wide" aria-live="polite"><div><small>Patient sélectionné</small><strong>{selectedPatient.fullName}</strong></div><dl><div><dt>CIN</dt><dd>{selectedPatient.cin}</dd></div><div><dt>Téléphone</dt><dd>{selectedPatient.phone}</dd></div><div><dt>Naissance</dt><dd>{selectedPatient.birthDate.slice(0,10)}</dd></div><div><dt>Adresse</dt><dd>{selectedPatient.address||"Non renseignée"}</dd></div></dl><Link to={`/patients/${selectedPatient.id}`}>Voir le dossier →</Link></div>}<label>Statut<select name="status" defaultValue="pending"><option value="pending">En attente</option><option value="confirmed">Confirmé</option></select></label><label>Motif<input name="reason" required/></label><label className="wide">Notes<textarea name="notes" rows={2}/></label>{error&&<div className="error wide" role="alert">{error}</div>}<button>Créer le rendez-vous</button></form>{success&&<div className="success" role="status">{success}</div>}<section className="card section"><div className="toolbar"><div className="appointment-filters"><input type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);setSuccess("")}}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);setSuccess("")}}><option value="">Tous les statuts</option><option value="pending">En attente</option><option value="confirmed">Confirmés</option><option value="cancelled">Annulés</option></select></div><span>{pagination.total} rendez-vous</span></div><AppointmentTable appointments={items} onStatus={change}/><div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(current=>current-1)}>Précédent</button><span>Page {page} / {pagination.totalPages}</span><button className="secondary" disabled={page>=pagination.totalPages} onClick={()=>setPage(current=>current+1)}>Suivant</button></div></section></Layout>
}
function AppointmentTable({appointments,onStatus}:{appointments:Appointment[];onStatus?:(id:string,s:string)=>void}){if(!appointments.length)return <Empty text="Aucun rendez-vous dans cette sélection."/>;return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Patient</th><th>Motif</th><th>Statut</th>{onStatus&&<th>Actions</th>}</tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{new Intl.DateTimeFormat("fr-MA",{timeZone:"Africa/Casablanca",dateStyle:"short",timeStyle:"short"}).format(new Date(a.appointmentDate))}</td><td><Link to={`/patients/${a.patientId}`}>{a.patientName}</Link></td><td>{a.reason}</td><td><span className={`badge ${a.status}`}>{a.status==="pending"?"En attente":a.status==="confirmed"?"Confirmé":"Annulé"}</span></td>{onStatus&&<td className="row-actions">{a.status!=="confirmed"&&<button onClick={()=>onStatus(a.id,"confirmed")}>Confirmer</button>}{a.status!=="cancelled"&&<button className="secondary" onClick={()=>onStatus(a.id,"cancelled")}>Annuler</button>}</td>}</tr>)}</tbody></table></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}function PageTitle({eyebrow,title,action}:{eyebrow:string;title:string;action?:ReactNode}){return <header className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{action}</header>}
export default function App(){return <AuthProvider><Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/patients" element={<Protected><Patients/></Protected>}/><Route path="/patients/:id" element={<Protected><PatientDetails/></Protected>}/><Route path="/appointments" element={<Protected><Appointments/></Protected>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></AuthProvider>}
